function add_class_proportions_to_plot(proportions)
    text(0.02, 0.9, sprintf('Klasa 1: %.2f%%\nKlasa 2: %.2f%%\nKlasa 3: %.2f%%', ...
        proportions(1), proportions(2), proportions(3)), ...
        'Units', 'normalized', 'FontSize', 10, 'BackgroundColor', 'w', 'EdgeColor', 'k');
end
