function [XNew, YPred] = predict_signal(model, processedSignal)
    % Przygotowanie danych wejściowych
    stats = processedSignal.statistics;
    XNew = [...
        stats.mean, ...
        stats.std, ...
        stats.skewness, ...
        stats.kurtosis, ...
        stats.median, ...
        stats.min, ...
        stats.max, ...
        stats.energy, ...
        stats.entropy];

    % Dokonanie predykcji
    YPred = predict(model, XNew);
end